### ISSUE TITLE
Lora module not ready

### ISSUE THREAD

**Issue by Carlgk1** [stm32duino/I-NUCLEO-LRWAN1#10]
Hello. I have an issue regarding my node. When I use the serial monitor, it says that the Lora module is not ready. I tried solving it with the solutions at the other thread but it did not still work. I am a newbie at LoRaWan. Please help.

I have a STM32F411 Nucleo-64 board and a I-NUCLEO-LRWAN1 shield. This is my setup.
![52755190_1212066382302308_7009686411494293504_n](https://user-images.githubusercontent.com/45568494/53182009-9a366980-3633-11e9-8817-f6c434635af1.jpg)

My serial monitors of LoRaWANABP and BridgeSerial
![123124](https://user-images.githubusercontent.com/45568494/53182081-bcc88280-3633-11e9-97d2-a93a3d278bd3.png)
![123asd21](https://user-images.githubusercontent.com/45568494/53182086-bfc37300-3633-11e9-91c6-d966d4d0f9e6.png)

Thank you.

**Comment by fpistm** [comment]
So the shield is not ready.
You should check which fw you have and probably update it.
https://github.com/USIWP1Module/USI_I-NUCLEO-LRWAN1/tree/master/preloaded_firmware

**Comment by Carlgk1** [comment]
Do I still need to buy this STLINK/V2 programmer?? The opencd-dev.exe file won't open and instantly closes when I try.

**Comment by fpistm** [comment]
If you have another nucleo board you can use its stlink by removing some jumper

**Comment by Carlgk1** [comment]
Can i use the nucleo board attached to the shield?? I don't have another nucleo board.

**Comment by fpistm** [comment]
Yes, in that case, i advise To not connect the shield on the board. Only power it.

**Comment by Carlgk1** [comment]
Hello. It seems that I still have no st-link/v2 connection as the St-link dongle has not shown up. 

My Device manager
![123asdxzc](https://user-images.githubusercontent.com/45568494/53468055-a2f3c900-3a93-11e9-9452-db88c5f5e931.png)

My current setup
![52720473_425603321314955_4322759020055101440_n](https://user-images.githubusercontent.com/45568494/53468230-4fce4600-3a94-11e9-9dfe-2b084be38afb.jpg)
![53082593_240327683516912_2031954894662926336_n](https://user-images.githubusercontent.com/45568494/53468232-50ff7300-3a94-11e9-82ee-f7bd74061121.jpg)


I removed the jumpers for the st-link connection in the nucleo board and connected it to the shield and I still can't open the opencd program

**Comment by fpistm** [comment]
> Hello. It seems that I still have no st-link/v2 connection as the St-link dongle has not shown up.

On your screenshot, I see STLink debug and the VCP.

Anyway, I've made a test with Nucleo-F411RE.
In fact the sketch require to be updated to use the BridgeSerial example.
On the Nucleo-F411RE, there is no U(S)ART on PC10/11.
You can try using PA11/PA12:
`HardwareSerial SerialLora(PA12, PA11);`
Then connect, PA12 to D0 and PA11 to D1.
![nucleo-f411re-i-lrwan](https://user-images.githubusercontent.com/20641798/53472472-ecc6ba00-3a67-11e9-9ca3-ea88b78a87a6.jpg)

![at-ilrwan](https://user-images.githubusercontent.com/20641798/53472738-ca816c00-3a68-11e9-85b9-4e87e8fbe27d.png)

I've updated some comments and README.md in #11 to avoid any confusion.
Per default, D0/D1 are the correct pins except for Nucleo 64 where user has to update SerialLora definition.

**Comment by fpistm** [comment]
Any update on this ?

**Comment by fpistm** [comment]
Close as no feedback since a while.
