### ISSUE TITLE
LoRaWANOTAA example not working ?

### ISSUE THREAD

**Issue by zielaq** [stm32duino/I-NUCLEO-LRWAN1#12]
Hello.
I have problem with LoRaWanOTAA example. nucleo-L452RE + I-Nucleo-lorawn1 (rx & tx connected to pc11 & pc10
i have only "joinOTAA failed!" 
There is is no needed devEUI ??

LoRaWANABP work fine (btw: how disable confirmation by downlink?)

**Comment by fpistm** [comment]
Hi,
To connect using OTAA, device and gateway require to use the same Application Key and Application EUI.
IIWR DevEUI is not used, your device should be registered to the gateway.
Do you read the Advice in the README.md ?
https://github.com/stm32duino/I-NUCLEO-LRWAN1#advice

Which LoRa FW version you used ? Which band ?
If LoRa FW is old I advise to update it.

**Comment by zielaq** [comment]
Yes a read advice. 
Lora FW: 2.6
band: LORA_BAND_EU_868

**Comment by fpistm** [comment]
So could you try update to 3.6. Thx

**Comment by zielaq** [comment]
I have tried to update (the newest is 3.7) but with no success. 
I tried to use stlink from nucleo-board L073RZ (without breaking the plate - only jumpers from cn2 removed) and connect cn4 (SWD with 4 pins VDD-TARGET, SWCLK, GND, SWDIO) with no success.
Also tried by simple ftdi and RX,TX also with no success. any suggestions ?

**Comment by fpistm** [comment]
It was a long time I've update it and remember I've met some issue.
I did the same than you.
Maybe you can try update the STLink fw also using the STM32CubeProgrammer.

**Comment by zielaq** [comment]
OK finally succeeded to update FW to 3.7. But still "joinOTAA failed" my gateway does not see any activity (i have other node on UNO and p-nucleo-lrwan1 and there gateway see join requests)

**Comment by fpistm** [comment]
Do you try to change the RX1 delay?
```
    RX1 window delay is 1000 ms by default. Use setRx1Delay() to set a new value.

In case of high latency between the gateway and the network server, it is recommended to increase the delay time of the RX1 window.
```

**Comment by zielaq** [comment]
Yes i tried this. No effect.

in LoraWANNode.cpp  in LoRaWANNodeClass::joinOTAA i have "ret" variable = 19 (hex)
So its goes to 
`do {
          if((millis() - timeout) > DELAY_FOR_JOIN_STATUS_REQ) {
            return 0;
          }
          ret = Lora_JoinAccept();
        } while(ret != AT_OK);
`
and this return 0 after timeout, but ret variable in this place have value (hex) "17"

**Comment by fpistm** [comment]
OK. As APBis working, I guess this is a settings issue when using the OTAA or a timing issue. When we release this library we met some issues around setting and timing. After looking deeply in the gateway settings we succeed to join properly.

**Comment by fpistm** [comment]
Regarding your last comment:
0x19 is `AT_JOIN_SLEEP_TRANSITION`
0x17 is `AT_UART_LINK_ERROR`

Regarding the code of `LoRaWANNodeClass::joinOTAA`:

```
  if(appKey != NULL) {
    keyCharToInt(appKey, key, 16);
    if(LoRa_SetKey(AT_APPKEY, key) == AT_OK) {
      ret = Lora_Join(OTAA_JOIN_MODE);
      if(ret == AT_OK) {  // Device joined
        return 1;
      } else if(ret == AT_JOIN_SLEEP_TRANSITION) {
        uint32_t timeout = millis();
        do {
          if((millis() - timeout) > DELAY_FOR_JOIN_STATUS_REQ) {
            return 0;
          }
          ret = Lora_JoinAccept();
        } while(ret != AT_OK);
        // HACK: enable again duty cycle
        setDutyCycle(true);
        return 1;
      }
    }
  }
```
So the join failed because it is in `AT_JOIN_SLEEP_TRANSITION`.
then it wait the join accept notification.
Finally it exits due to timeout with ret = 0x17 (`AT_UART_LINK_ERROR`)
This error come from the fact there is no answers from the Lora module.
```
  while (!ResponseComplete) {
    msStart = millis();
    while (!HW_UART_Modem_IsNewCharReceived()) {
      if((millis() - msStart) > RESPONSE_TIMEOUT) {
        return AT_UART_LINK_ERROR;
      }
    }
```
So, it's hard to help as I'm not able to reproduce.
You can try to enable the `DBG_PRINTF` by defining `DEBUG` and `TRACE` 
To see if at least you get some answers to the join accept.

**Comment by fpistm** [comment]
Hi @zielaq 
any update on this ?

**Comment by fpistm** [comment]
Close as no feedback since a while and not reproducible.
