### ISSUE TITLE
receive and transmit

### ISSUE THREAD

**Issue by zielaq** [stm32duino/I-NUCLEO-LRWAN1#13]
Hello.
Mayby this is not an issue but i don't known how it works.

Why in example receive is before transmit since the gate first receives and then sends data ( when we use downlink to transmit data).

Is it that the data received is still in the buffer (in the node) and are read from this buffer only before the next transmit?

**Comment by fpistm** [comment]
Hi @zielaq 
Honestly, I don't know.
This library was originally implemented by [Wi6labs](http://www.wi6labs.com/en/) company which are 
specialized in wireless technologies and member of the [LoRa Alliance™](https://www.lora-alliance.org/)
Referring to the function comment header `receiveFrame `have to be call before `sendFrame`, probably linked to LoRa specification.
https://github.com/stm32duino/I-NUCLEO-LRWAN1/blob/fcdf82611a80c114a5d6ff33eb5112367ec530e4/src/LoRaWANNode.cpp#L231-L239

**Comment by zielaq** [comment]
Ok. thanks. 
I was wondering about this because as we will give a long time between the transmit we will have the same delayed feedback

**Comment by zielaq** [comment]
Ok this is clear. 
I have tested first transmit, add little delay and then receive and i look's like this is also working.
