### ISSUE TITLE
frequency hopping in ADR mode

### ISSUE THREAD

**Issue by zielaq** [stm32duino/I-NUCLEO-LRWAN1#14]
can i add more frequency (channels) for hopping in this mode ? 
In my observations its use only 3 channels (868.1 868.3 and 868.5).

**Comment by fpistm** [comment]
Hi @zielaq 
I don't know really this. This is too precise for me 😆 
Anyway, in [WM-SG-SM-42 AT Command Reference Manual](https://github.com/USIWP1Module/USI_I-NUCLEO-LRWAN1/blob/master/WM-SG-SM-42%20AT%20Command%20Reference%20Manual%20rev.2.3_20180701.pdf):
![image](https://user-images.githubusercontent.com/20641798/55401506-4895ce80-5551-11e9-9729-5c10c46ac7d0.png)

I advise you to open a issue on their GitHub repo for more info:
https://github.com/USIWP1Module/USI_I-NUCLEO-LRWAN1

**Comment by zielaq** [comment]
Ok thanks ;)

**Comment by fpistm** [comment]
Welcome 👍
