### ISSUE TITLE
Problem with sending message longer than 4 characters & Problem with firmware update

### ISSUE THREAD

**Issue by Tyluuus** [stm32duino/I-NUCLEO-LRWAN1#15]
Hi, 

I've got 2 I-Nucleo-LRWAN1 shields on 2 STM32 Nucleo64 F103-RB boards. I've uploaded PingPong example and it works but I've tried to modify code and send longer message (for example "ABCDEFG123") and what i receive on second board is first four characters "ABCD". 

I checked module by BridgeSerial and it works. It's software version: 2.9.

I cannot update firmware to newer version, after connection to ST-Link on STM32 Board there is info in ST-Link utility that it has Read Out Protection.

I also paste my simple code I used for testing.

Tx:
```C++
#include "LoRaRadio.h"
#define SEND_PERIOD_MS 2000

HardwareSerial SerialLora(PC_11, PC_10);


uint8_t Message[] = "ABCDEFGH";
//uint8_t len=0;
//int timer=0;
//uint8_t x=0;

void setup() {
  Serial.begin(115200);
  Serial.println("!! Tx !!");

  while(!loraRadio.begin(&SerialLora)) {
    Serial.println("LoRa module not ready");
    delay(1000);
  }

  Serial.println("LoRa module ready\n");
  }
//  len=sizeof(Message);
//  loraRadio.write(Message,len);
//  timer=millis();
//

void loop() {
 //len=sizeof(Message);
  loraRadio.write(Message,9);
  Serial.println("Message sent : ");
  //Serial.println(x);
 delay(3000);

}
```

Rx:
```C++
#include "LoRaRadio.h"

HardwareSerial SerialLora(PC_11, PC_10);


//uint8_t x=0;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  Serial.println("!! Rx !!");

  while(!loraRadio.begin(&SerialLora)) {
    Serial.println("LoRa module not ready");
    delay(1000);
  }

  
  Serial.println("LoRa module ready\n");
}
//  if(loraRadio.read(rcvData) > 0) {
//    Serial.println((char *) rcvData);
//  }
//}

void loop() {
  
  uint8_t rcvData[64];
  
  // put your main code here, to run repeatedly:
  if(loraRadio.read(rcvData) > 0){
      Serial.println("Receiver");
      Serial.println((char *)rcvData);
      delay(500);
      Serial.println((char *)rcvData);
  }
    
  //Serial.println((char *)rcvData);
 // if(x > 0) {
    //Serial.println((char *) rcvData);
    
    
   // Serial.println(x);
    
  memset(rcvData, 0, 10);
   delay(1000);
  
}

```
I'd be grateful for any help.
Thanks in advance!
T.

**Comment by fpistm** [comment]
Hi @Tyluuus 
The latest version of fw I've check was 2.9 IIWR. 
I'm not aware there is newer version and this will need to be tested as probably some AT commands has changed.

For the Read out protection I don't know. You could file an issue to https://github.com/USIWP1Module/USI_I-NUCLEO-LRWAN1/issues to ask how fix this.

For the message length, this will required to be tested. I will not be able to do that soon as I've a lot of other stuff to do before and I will be 2 weeks off for vacation. But this will be investigated. Thanks for the report.

**Comment by Tyluuus** [comment]
Hi @fpistm,

I successfully updated firmware to version 3.7, but still have a problem with sending messages longer than 4 bytes. Even after adding 1 additional byte to PingPong excample and changing number of bytes in memcmp, memset and write functions program doesn't send any messages.

T.

**Comment by fpistm** [comment]
Hi @Tyluuus 
I will get soon 2 shield and so I will be able to test. I will come back to you when I could.
