### ISSUE TITLE
AS923 Support

### ISSUE THREAD

**Issue by shmrymbd** [stm32duino/I-NUCLEO-LRWAN1#16]
Hi,
I cant find any information for the support of AS923. Pls advice

**Comment by fpistm** [comment]
Hi @shmrymbd ,

You should check you FW version, it seems supported since version 3.4/3.5
https://github.com/USIWP1Module/USI_I-NUCLEO-LRWAN1/blob/4a0279ee043060897a489cf5d63ccfb77201a090/preloaded_firmware/CHANGELOG.txt#L95

**Comment by shmrymbd** [comment]
hi sorry.. any manual how to direct connect with AT command using Nucleo.

**Comment by fpistm** [comment]
You can use this example:
https://github.com/stm32duino/I-NUCLEO-LRWAN1/blob/master/examples/BridgeSerial/BridgeSerial.ino

Pay attention on the   **Important note for Nucleo64.**

**Comment by fpistm** [comment]
Close. considered as answered.
