### ISSUE TITLE
Only  US and EU frequency are supported!

### ISSUE THREAD

**Issue by tejeshw** [stm32duino/I-NUCLEO-LRWAN1#17]
source code not supporting  other frequency

**Comment by fpistm** [comment]
Hi @tejeshw 
yes this is specified in the README.md.

> Select the EU or US band.

When the library was created the FW does not support other freq.

> Version
> 
> This library is based on the STM32CubeExpansion_LRWAN_V1.1.2 driver. This library has been validated with the version 2.6 and 3.6 of the firmware.
> 

Feel free to submit a PR.
