### ISSUE TITLE
Send message in OTAA mode

### ISSUE THREAD

**Issue by Zhang-esigelec** [stm32duino/I-NUCLEO-LRWAN1#18]
Hello,

Im using I-nuclei-lrwan1 with a nucleo64 l073rz board, I want to know how to send bytes via the OTAA, because I find only the function sendFrame in the example. Thank you so much!

**Comment by fpistm** [comment]
Use the only LoRa Radio as in the example:
https://github.com/stm32duino/I-NUCLEO-LRWAN1/blob/main/examples/LoRaPingPong/LoRaPingPong.ino

With OTAA you can only sendFrame with this library.
