### ISSUE TITLE
Cannot compile 

### ISSUE THREAD

**Issue by OlegZv** [stm32duino/I-NUCLEO-LRWAN1#2]
When I try to compile RAW example get devEUI I get:
```
getDevEUI:27: error: 'PA_0' was not declared in this scope
 HardwareSerial SerialLora(PA_1, PA_0);
```

I tried to declare PA_1 and PA_0 as 23 and 22. I get next error when compiling:
```
exit status 1
no matching function for call to 'HardwareSerial::HardwareSerial(int&, int&)'
```

Any idea why is that happening? I didn't change anything, but want to get a terminal to sent AT commands and receive commands.

**Comment by fpistm** [comment]
Hi @OlegSomov 
Which core you used?
I think you used @rogerclarkmelbourne  core:
https://github.com/rogerclarkmelbourne/Arduino_STM32
That's why you have this error.
This library is mainly for this core:
https://github.com/stm32duino/Arduino_Core_STM32

**Comment by fpistm** [comment]
Closed as no feedback.
