### ISSUE TITLE
I-NUCLEO-LRWAN1 as Gateway?

### ISSUE THREAD

**Issue by borombo96** [stm32duino/I-NUCLEO-LRWAN1#7]
Hi, 
is possible to configura the I-NUCLEO-LRWAN1 , maybe with a raspberry, to works like a LoRa gateway?

**Comment by fpistm** [comment]
This depends to what you mean by LoRa gateway. A gateway like, it's probably be possible,  a full qualified Gateway I don't think :)
Anyway it should probably a good idea to submit this also to https://github.com/USIWP1Module/USI_I-NUCLEO-LRWAN1
