### ISSUE TITLE
Problem SoftwareSerial

### ISSUE THREAD

**Issue by borombo96** [stm32duino/I-NUCLEO-LRWAN1#8]
Hi, I'm a student, I'm using the I-NUCLEO-LRWAN1 in my application, all it's working but I have a problem.
For my application I need to send AT comand to an other board ( sim7000), so I have to use an other serial to send this command. With Arduino I can do this using the SoftwareSerial library, but here I can't do this (Why? SoftwareSerial is not supported? ).
I know that with my hardware I have 3 (?) USART periphericals and I can set one of this to send this AT commands but I don't know how.
I'm using the serial bridge with wires that connects D0 and D1 to PC_11 and PC_10. In the pin map I see that D0 and D1 are usart2 and PC_11 and PC_10 are usart1; maybe is this the problem?
I try to write something like 
`#define mySerial Serial2` 
that in the pin map they are PA_15 and PA_14 but when I program it to send "AT" with 
`mySerial.write("AT \r\n");` 
I see the message in the COM port of STM but I don't see nothing in PA_15 and PA_14; I'm confused.
Ty for the help.

**Comment by fpistm** [comment]
Hi,
Software Serial is currently not supported. Request already open for that:
https://github.com/stm32duino/Arduino_Core_STM32/issues/267
Don't know which Board you have but if you have unused U(S)ART, simply define an instance to use it:
`HardwareSerial SerialForSim7000(rxpin, txpin);`

Then:
```
SerialForSim7000.begin(baudrate);
SerialForSim7000.write("AT \r\n");
```

**Comment by borombo96** [comment]
Ty for help.
Now I'm able to write on an other USART. I'm trying with this code:
`HardwareSerial SerialForSim7000(PA_10, PA_9);
void setup() {
  Serial.begin(9600);
  SerialForSim7000.begin(9600);
  // put your setup code here, to run once:

}

void loop() {
  SerialForSim7000.write("AT \r\n");
  Serial.write("comand send");
  Serial.println();
  delay(1000);
  Serial.write(SerialForSim7000.read());
  Serial.println();
  delay(2000);

}`

but the output is this: 
![image](https://user-images.githubusercontent.com/40265864/43260101-c507630e-90d8-11e8-8173-e5f5e44c7b29.png)

I'm using STM32L053R8.
I also tried with a bridge serial-usb and I readed on the com of bridge the command, so the command is sended but I have problem to read the reply. 
With Arduino I used 'readStringUntil' but here it doesn't work.
Ty for help.

**Comment by fpistm** [comment]
This is normal as read return char by char.
Try to use something like that:

```
while(SerialForSim7000.available())
  Serial.write(SerialForSim7000.read());
```

Anyway, this is not the right place to discuss about that. I saw you registered on the forum; please use it for this kind of questions.
Here, this is a place to raise issue on I Nucleo LRWAN1 library.

**Comment by borombo96** [comment]
Ok ty, I'll open a post on forum. :)
