### ISSUE TITLE
Problem removing alimentation

### ISSUE THREAD

**Issue by borombo96** [stm32duino/I-NUCLEO-LRWAN1#9]
Hi, I programmed this expansion board with Nucleo-L053R8. It's work but if I remove and I reconnect the board I don't see anything on terminal.
Why?

**Comment by fpistm** [comment]
Could you be more explicit on your issue, step by step.
If your issue is to unplug the L053 then re-plug it and you do not see anything on the terminal, this is probably because you do not close your terminal as the VCP disappears and reappears.

**Comment by borombo96** [comment]
Yes, my issue is this.
I program the board with my codes, it works, I send data sensor and an other board receive it and I see all of this on terminal. 
Then I close the terminal, I unplug the tx board and I replug it, but it doesn't work, I don't see nothing on terminal and the rx board doesn't receive nothing.
Ty 4 help

**Comment by fpistm** [comment]
Seems like the MCU is not properly reset...
What happen if you press reset button?
Update the STLink firmware also.

**Comment by borombo96** [comment]
when I push reset doesn't happen nothing.
Anyway with an other expansion board with new firmware it works. 
do u think that the problem is on st link of the nucleo or on the expansion board?

**Comment by fpistm** [comment]
Hard to answer.
But if the same board (Nucleo-L053R8) it works with one expansion board but not with an other.
This probably due to expansion board.
You can try to update the expansion board firmware:
https://github.com/USIWP1Module/USI_I-NUCLEO-LRWAN1/tree/master/preloaded_firmware

**Comment by borombo96** [comment]
I try to use only the nucle with an example for serial, and it doesn't work when I replug it. Is it the nucleo so? Can I update firmware of ST Link on nucleo maybe? 
ty 4 help

**Comment by fpistm** [comment]
Yes.
I've tested on Linux and Windows without any issue.

**Comment by fpistm** [comment]
Hi @borombo96 ,
Any update on this ?

**Comment by borombo96** [comment]
Hi, now I can't work on this but next week I'll try to update the st link firmware of the not working board.
Ty 4 help

**Comment by fpistm** [comment]
Ok thanks.
Let me know the status ;)

**Comment by borombo96** [comment]
hi, other different question.
Is there any function to get power of reception in dB? 
I set the power on tx 20dB and I want to see the power on rx when I go far. Ty 4 help

**Comment by fpistm** [comment]
@borombo96 ,
this is a place to discuss an dedicated issue not a forum.
Please use the forum to ask those kind of things. IAnyway, I do not remember well but I think there is
no High API to get. I advice to search in the code.

**Comment by fpistm** [comment]
No update since a while and issue never reproduced.
